import mon1 from '../../assets/images/dishs/mon1.jpg';
import mon2 from '../../assets/images/dishs/mon2.jpg';
import mon3 from '../../assets/images/dishs/mon3.jpg';
import mon4 from '../../assets/images/dishs/mon4.jpg';
import mon5 from '../../assets/images/dishs/mon5.jpg';
import mon6 from '../../assets/images/dishs/mon6.jpg';
import mon7 from '../../assets/images/dishs/mon7.jpg';
import mon8 from '../../assets/images/dishs/mon8.jpg';
import mon9 from '../../assets/images/dishs/mon9.jpg';

const fakeListDish = [
     {
          id: 1,
          name: "Set a India vegetable",
          des: '',
          mealTime: 1,
          price: '$25.99',
          src: mon1,
          like: true,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
     },
     {
          id: 2,
          name: "Indonesian salad",
          des: '',
          mealTime: 2,
          price: '$25.99',
          src: mon2,
          like: false,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
     },
     {
          id: 3,
          name: "Fresh vegetables",
          des: '',
          mealTime: 3,
          price: '$25.99',
          src: mon3,
          like: true,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
     },
     {
          id: 4,
          name: "Salad mixed sauce",
          des: '',
          mealTime: 4,
          price: '$25.99',
          src: mon4,
          like: false,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
     },
     {
          id: 5,
          name: "Healthy bread with salad",
          des: '',
          mealTime: 1,
          price: '$25.99',
          src: mon5,
          like: false,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
     },
     {
          id: 6,
          name: "Organic noodles egg",
          des: '',
          mealTime: 2,
          price: '$25.99',
          src: mon6,
          like: false,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
     },
     {
          id: 7,
          name: "Set a Japanese vegetable",
          des: '',
          mealTime: 3,
          price: '$25.99',
          src: mon7,
          like: true,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
     },
     {
          id: 8,
          name: "Healthy egg with salad",
          des: '',
          mealTime: 4,
          price: '$20.99',
          src: mon8,
          like: false,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Beverages', 'Pasta'],
     },
     {
          id: 9,
          name: "Oriental salad medium",
          des: '',
          mealTime: 1,
          price: '$19.99',
          src: mon9,
          like: true,
          check: true,
          time: '12 mm',
          star: ' 4.5 / 755',
          allergenic: 'egg',
          group: ['Asian', 'Chicken', 'Alcohol', 'Pasta'],
     },

]

export default fakeListDish
